version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:0.11.12
        entrypoint: /bin/sh
    steps:
      - checkout
      - run:
          name: checks
          command: |
            cd ./modules/k8s
            terraform init \
              -backend-config="access_key=$SPACES_ACCESS_TOKEN" \
              -backend-config="secret_key=$SPACES_SECRET_KEY" \
              -backend-config="bucket=$SPACES_BUCKET_NAME" \
              -backend-config="endpoint=$SPACES_ENDPOINT"
            terraform validate
            terraform plan

  deploy:
    docker:
      - image: hashicorp/terraform:0.11.12
        entrypoint: /bin/sh
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  test-deploy:
    jobs:
      - validate
      - deploy:
          requires:
            - validate
          filters:
            branches:
              only: /^master$/
