deploy: &deploy
    docker:
      - image: hashicorp/terraform:${TERRAFORM_VERSION}
        entrypoint: /bin/sh
    steps:
      - checkout
      - run:
          name: dependencies
          environment:
            KUBECTL_VERSION: v1.13.4
            HELM_VERSION: v2.13.1
          command: |
            apk add --no-cache curl

            curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl

            wget https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz && \
            tar zxfv helm-${HELM_VERSION}-linux-amd64.tar.gz && \
            chmod a+x ./linux-amd64/helm
            mv ./linux-amd64/helm /usr/local/bin/helm
      - run:
          name: deploy
          command: |
            ./scripts/deploy.sh

version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:0.11.12
        entrypoint: /bin/sh
    steps:
      - checkout
      - run:
          name: checks
          command: |
            cd ./modules/w3f
            terraform init \
              -backend-config="access_key=$SPACES_ACCESS_TOKEN" \
              -backend-config="secret_key=$SPACES_SECRET_KEY" \
              -backend-config="bucket=$SPACES_BUCKET_NAME" \
              -backend-config="endpoint=$SPACES_ENDPOINT"
            terraform validate
            terraform plan

  w3fDeploy:
    environment:
      DEPLOYMENT: w3f
      TERRAFORM_VERSION: 0.11.12
    <<: *deploy

  communityDeploy:
    environment:
      DEPLOYMENT: community
      TERRAFORM_VERSION: 0.11.12
    <<: *deploy

  developmentDeploy:
    environment:
      DEPLOYMENT: development
      TERRAFORM_VERSION: 0.12.4
    <<: *deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - validate
      - w3fDeploy:
          requires:
            - validate
          filters:
            branches:
              only: /^master$/
      - communityDeploy:
          requires:
            - validate
          filters:
            branches:
              only: /^master$/
      - developmentDeploy:
          requires:
            - validate
          filters:
            branches:
              only: /^master$/
