deploy: &deploy
    docker:
      - image: hashicorp/terraform:0.12.5
        entrypoint: /bin/sh
    steps:
      - checkout
      - run:
          name: dependencies
          environment:
            KUBECTL_VERSION: v1.13.4
            HELM_VERSION: v2.13.1
          command: |
            apk add --update-cache --upgrade curl

            curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl

            wget https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz && \
            tar zxfv helm-${HELM_VERSION}-linux-amd64.tar.gz && \
            chmod a+x ./linux-amd64/helm
            mv ./linux-amd64/helm /usr/local/bin/helm
      - run:
          name: deploy
          command: |
            ./scripts/deploy.sh

validate: &validate
    docker:
      - image: hashicorp/terraform:0.12.5
        entrypoint: /bin/sh
    steps:
      - checkout
      - run:
          name: checks
          command: |
            ./scripts/validate.sh $BACKEND_CONFIG

version: 2
jobs:
  communityValidate:
    environment:
      DEPLOYMENT: community
    <<: *validate

  w3fValidate:
    environment:
      DEPLOYMENT: w3f
    <<: *validate

  developmentValidate:
    environment:
      DEPLOYMENT: development
    <<: *validate

  developmentRunnersValidate:
    environment:
      DEPLOYMENT: development-runners
    <<: *validate

  engineeringValidate:
    environment:
      DEPLOYMENT: engineering
    <<: *validate

  w3fDeploy:
    environment:
      DEPLOYMENT: w3f
    <<: *deploy

  communityDeploy:
    environment:
      DEPLOYMENT: community
    <<: *deploy

  developmentDeploy:
    environment:
      DEPLOYMENT: development
    <<: *deploy

  developmentRunnersDeploy:
    environment:
      DEPLOYMENT: development-runners
    <<: *deploy

  engineeringDeploy:
    environment:
      DEPLOYMENT: engineering
    <<: *deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - communityValidate:
          filters:
            tags:
              only: /.*/
      - w3fValidate:
          filters:
            tags:
              only: /.*/
      - developmentValidate:
          filters:
            tags:
              only: /.*/
      - developmentRunnersValidate:
          filters:
            tags:
              only: /.*/
      - engineeringValidate:
          filters:
            tags:
              only: /.*/
      - w3fDeploy:
          requires:
            - w3fValidate
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - communityDeploy:
          requires:
            - communityValidate
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - developmentDeploy:
          requires:
            - developmentValidate
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - developmentRunnersDeploy:
          requires:
            - developmentRunnersValidate
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - engineeringDeploy:
          requires:
            - engineeringValidate
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
